[project]
name = "ftl"
version = "0.1.0"
description = "FFMPEG encoding simplified."
readme = "README.md"
authors = [
    { name = "Dan Bradham", email = "danielbradham@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "attrs>=25.4.0",
    "cattrs>=25.3.0",
    "dearpygui>=2.1.1",
    "platformdirs>=4.5.1",
    "pyautogui>=0.9.54",
    "pytest>=9.0.2",
    "typeguard>=4.4.4",
    "typer>=0.21.1",
]
license = "MIT"
license-files = ["LICENSE"]

[tool.uv]
package = true

[project.scripts]
ftl = "ftl.__main__:cli"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
